### ISSUE TITLE
[UP Ext] Approving ERC20 token crashes extension

### ISSUE THREAD

**Issue by lykhonis** [lukso-network/issue-tracker#1]
version: v1.0.0-develop.260-MV3
browser: chrome

I am using a contract that is ERC20 on L16. I am sending ERC20 approve transaction. Attaching a moment I send ERC20 approve tx.

https://user-images.githubusercontent.com/881338/179250730-f422552b-a2e9-4507-9308-9a093fca4f52.mov

**Comment by lykhonis** [comment]
This is the only error from extension that shows up when this happens: 
<img width="639" alt="Screen Shot 2022-07-21 at 00 08 35" src="https://user-images.githubusercontent.com/881338/180128134-4d0bf394-1428-4030-bdf9-5d020228a600.png">

All my code does:
```
export const approve = async (
  web3: Web3,
  profile: string,
  spender: string,
  amount: string | BN
) => {
  const method = getContract(web3).methods.approve(spender, amount)
  const gas = adjustGasEstimate(await method.estimateGas({ from: profile }))
  const { maxFeePerGas, maxPriorityFeePerGas } = await getFeeData(web3)
  return await method.send({
    from: profile,
    gas,
    maxFeePerGas,
    maxPriorityFeePerGas
  })
}
```

where:
- profile is UP address
- spender is my contract
- amount is BigNumber in wei of token to approve

**Comment by Hugoo** [comment]
Thanks @lykhonis - we are working on it

**Comment by Hugoo** [comment]
We added this issue in our tracking system under ID: `#2nv74b5`

**Comment by lykhonis** [comment]
FYI this issue can be debugged here: https://relayer-frontend.vercel.app/. You would need to deposit some LYXt, once you receive rLYX, you will see button to approve to trigger the issue. You may need to wait up to 1 hour to receive rLYX.

**Comment by olusoladavid** [comment]
@lykhonis Can you confirm that this issue is happening in the MV2 [latest release](https://docs.lukso.tech/guides/browser-extension/install-browser-extension) ? By the way, I tried to get some rLYX but it's been over 12 hours and no success:

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/30433120/186363401-e7c0df79-2396-4701-9739-2283ee0f5bc2.png">

**Comment by lykhonis** [comment]
Hello, I had to stop rewards. I've restarted, you should have received some:
```
1|rewards  | Submitting rewards: 0x506fb98634903caac59e2e02b955e13cac0e3cbf (0.01 rLYX), fees: 1500000014 (1500000000)
1|rewards  | Submitting rewards: 0x6df1986e581ef43ce67124996cab6ddd3cd09677 (0.01 rLYX), fees: 1500000014 (1500000000)
1|rewards  | Submitting rewards: 0xd924c6f46c6641950f6034f827d8ef2a63e6fccc (0.01 rLYX), fees: 1500000014 (1500000000)
1|rewards  | Submitting rewards: 0x6c609f39bdfdc3500222b114129c5c1c6aa6becd (0.01 rLYX), fees: 1500000014 (1500000000)
1|rewards  | Submitting rewards: 0x1d12e5e93ba4caa80406da4b1b95578bb1b9d799 (0.01 rLYX), fees: 1500000014 (1500000000)
1|rewards  | Submitting rewards: 0xcc97d9531f8b3d491bcddd995d235a48ccc35796 (0.01 rLYX), fees: 1500000014 (1500000000)
1|rewards  | Submitting rewards: 0x1c76b6af7a1e0068e0dfbaef2b80b95a3b8b60a1 (0.01 rLYX), fees: 1500000014 (1500000000)
1|rewards  | Submitting rewards: 0x686c7957cb6b22ebe74de36632a7047f87c1c2c5 (0.01 rLYX), fees: 1500000014 (1500000000)
1|rewards  | Tx hash: 0x686c7957cb6b22ebe74de36632a7047f87c1c2c5 - 0xd266c1807ef86acb96dda48c927d2eb1d31052afe13fc122e663f25c57b40aab
1|rewards  | Tx hash: 0x1c76b6af7a1e0068e0dfbaef2b80b95a3b8b60a1 - 0xf87f8e89d37bff324855ed8489fa1ff8f6312f487bf7ba19d5b4aed4af08e452
1|rewards  | Tx hash: 0x1d12e5e93ba4caa80406da4b1b95578bb1b9d799 - 0x4cccc2033124ca62378f2a7c4c70c4298203f01fbf9079b189f23342e6139d5a
1|rewards  | Tx hash: 0xd924c6f46c6641950f6034f827d8ef2a63e6fccc - 0x438b3bcf9d7fb6d3bc451142e22f580d271df9e3963c4c433ad6d918b4579e89
1|rewards  | Tx hash: 0xcc97d9531f8b3d491bcddd995d235a48ccc35796 - 0xdb13e43474f54e148e342aaee6a0875ac89a1b1b9fc9df71fe3bb07165d21d70
1|rewards  | Tx hash: 0x506fb98634903caac59e2e02b955e13cac0e3cbf - 0xafba9376b0c581d5bdacd6f3ad73b64d700414bd1c9580df58a1dd70f5b1ee4c
1|rewards  | Tx hash: 0x6df1986e581ef43ce67124996cab6ddd3cd09677 - 0xfd48c1a7ef50fb0da29552e380221ddad0c54ef4f54f35ab69692402b59b6138
1|rewards  | Tx hash: 0x6c609f39bdfdc3500222b114129c5c1c6aa6becd - 0xaf3494a46eb00d792767763f78cae473f4a120ca37dbb78af5ea3101b14768bb
```
if your address is here :)

**Comment by olusoladavid** [comment]
Thanks for the quick response @lykhonis . I can't see a button to `Approve` though. Do I have to do something to get it to show?

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/30433120/186591455-7a0e70c5-958e-44b8-a351-dd4b183a66a3.png">

**Comment by lykhonis** [comment]
@olusoladavid it should be on profile page

**Comment by olusoladavid** [comment]
Yeah, @lykhonis . I can confirm that this issue is happening in the latest build and has been ticketed. You are correct, the issue has to do with how we handle contracts that have a non-LSP interface like ERC20. We are working on better UX for non-LSP contracts, and we will release this as soon as we are able to. Thanks

PS: I did manage to get the `approve` transaction to work but the rLYX was not deducted. Is that the expected behavior?

**Comment by lykhonis** [comment]
It won't deduct unless you add relayer service or use /debug page to make transactions through the relayer

**Comment by Hugoo** [comment]
hey Vlad - I tried to deposit a few LYXt but got this error:
<img width="862" alt="image" src="https://user-images.githubusercontent.com/477945/216350574-d4499193-dcfe-4f78-a695-f0eb7ddd5591.png">

Is the project still up? (The red error is a "smart contract error"). I didn't look further but yeah if you could simply tell me if it is still running as usual so I can try again or not.

Thanks!

**Comment by lykhonis** [comment]
I think this has been fixed. And no, it does not run properly anymore. Though this is depositing which should still work.

**Comment by Hugoo** [comment]
Thanks for the quick update! I will close this issue then. :)
