### ISSUE TITLE
Password error when i try export my private key

### ISSUE THREAD

**Issue by coffiasd** [lukso-network/issue-tracker#10]
I got another issue when i try to export private key from UP browser EXT , and then he told me password error . Is this password means login password ? I just use this password to login , I don't know why he told me password error
I'm quite sure my password is right

**Comment by dzbo** [comment]
Yes, for export PK you use same password as for the login. Under the hood we use same check in both cases, are you sure you use same one?

**Comment by coffiasd** [comment]
I’m very sure &nbsp;I used the same password cause I tried so many time login and the export key



发自我的iPhone


------------------ Original ------------------
From: Dominik Zborowski ***@***.***&gt;
Date: Fri,Aug 5,2022 9:03 PM
To: lukso-network/issue-tracker ***@***.***&gt;
Cc: coffiasd ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [lukso-network/issue-tracker] Password error when i try export myprivate key (Issue #10)

**Comment by dzbo** [comment]
> I’m very sure &nbsp;I used the same password cause I tried so many time login and the export key 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Dominik Zborowski ***@***.***&gt; Date: Fri,Aug 5,2022 9:03 PM To: lukso-network/issue-tracker ***@***.***&gt; Cc: coffiasd ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [lukso-network/issue-tracker] Password error when i try export myprivate key (Issue #10)

I'll check, which build are you using atm? 260?

**Comment by wavedashprime** [comment]
Did you try removing the extension and starting from scratch? I don't know if it helps but I had the same problem and this is one of the things I did before it started working as expected.

**Comment by coffiasd** [comment]
> Did you try removing the extension and starting from scratch? I don't know if it helps but I had the same problem and this is one of the things I did before it started working as expected.

Yes sir I reinstalled the EXT and it's okay now thank you

**Comment by coffiasd** [comment]
> > I’m very sure &nbsp;I used the same password cause I tried so many time login and the export key 发自我的iPhone
> 
> > […](#)
> 
> > ------------------ Original ------------------ From: Dominik Zborowski ***@***.***&gt; Date: Fri,Aug 5,2022 9:03 PM To: lukso-network/issue-tracker ***@***.***&gt; Cc: coffiasd ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [lukso-network/issue-tracker] Password error when i try export myprivate key (Issue #10)
> 
> 
> 
> I'll check, which build are you using atm? 260?

Yes it 260 after my reinstall it is okay now

**Comment by coffiasd** [comment]
I’m not sure the building version i will reply you later&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Dominik Zborowski ***@***.***&gt;
Date: Fri,Aug 5,2022 9:07 PM
To: lukso-network/issue-tracker ***@***.***&gt;
Cc: coffiasd ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [lukso-network/issue-tracker] Password error when i try export my private key (Issue #10)





  
I’m very sure &nbsp;I used the same password cause I tried so many time login and the export key 发自我的iPhone
 …
 ------------------ Original ------------------ From: Dominik Zborowski @.&gt; Date: Fri,Aug 5,2022 9:03 PM To: lukso-network/issue-tracker @.&gt; Cc: coffiasd @.&gt;, Author @.&gt; Subject: Re: [lukso-network/issue-tracker] Password error when i try export myprivate key (Issue #10)
  
I'll check, which build are you using atm? 260?
