### ISSUE TITLE
Pictures not uploading on Firefox

### ISSUE THREAD

**Issue by skimaharvey** [lukso-network/issue-tracker#12]
I am trying to add a profile pic to my UP through the UP extension on firefox. It does not work, I tried with a 19kb image. Nothing happens when I add it however when I click on there, I can see the pic is cached within the UP extension but can't actually find it within my LSP3Profile values. 

For example, with the 0x546b77b899c8feb644a45cE659dF7F83668F524a UP. 

<img width="388" alt="Screenshot 2022-08-08 at 13 20 43" src="https://user-images.githubusercontent.com/64636974/183396743-72e074f6-ac36-4ec8-8f57-e664135f2643.png">

**Comment by dzbo** [comment]
https://app.clickup.com/t/2t29uk3

**Comment by dzbo** [comment]
Done
