### ISSUE TITLE
[UP ext] Add Sign in With Ethereum custom sign window

### ISSUE THREAD

**Issue by frozeman** [lukso-network/issue-tracker#13]
We could show a custom "Login" window, when users request a messaged to be signed using [Sign in with ethereum](https://docs.login.xyz).

https://docs.login.xyz/sign-in-with-ethereum/quickstart-guide/implement-the-frontend

```js
function createSiweMessage (address, statement) {
  const message = new SiweMessage({
    domain,
    address,
    statement,
    uri: origin,
    version: '1',
    chainId: '1'
  });
  return message.prepareMessage();
}
```

SIW EIP is 4361: https://docs.login.xyz/general-information/siwe-overview/eip-4361

Input is:
```
sign-in-with-ethereum =
    domain %s" wants you to sign in with your Ethereum account:" LF
    address LF
    LF
    [ statement LF ]
    LF
    %s"URI: " uri LF
    %s"Version: " version LF
    %s"Chain ID: " chain-id LF
    %s"Nonce: " nonce LF
    %s"Issued At: " issued-at
    [ LF %s"Expiration Time: " expiration-time ]
    [ LF %s"Not Before: " not-before ]
    [ LF %s"Request ID: " request-id ]
    [ LF %s"Resources:"
    resources ]
```

Output (We can do better :)):
```
service.org wants you to sign in with your Ethereum account:
0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
​
I accept the ServiceOrg Terms of Service: https://service.org/tos
​
URI: https://service.org/login
Version: 1
Chain ID: 1
Nonce: 32891756
Issued At: 2021-09-30T16:25:24Z
Resources:
- ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/
- https://example.com/my-web2-claim.json
```

The recovery of the signed messages, has to happen over the `isValidSignature()` function, rather than `ecrecover`.

Later we want to add a proper two way sign protocol. but this could serve as a simple step towards a better login experience.

@Leondroids

**Comment by frozeman** [comment]
Even 1271 is proposed, which we use in LSP0:

<img width="769" alt="Screenshot 2022-08-12 at 11 49 19" src="https://user-images.githubusercontent.com/232662/184329930-2dbf1d20-26f1-453c-83dd-ab750eea58b9.png">

**Comment by frozeman** [comment]
First basic design draft for the login screen using SIWE:
<img width="249" alt="Screenshot 2022-08-24 at 13 44 33" src="https://user-images.githubusercontent.com/232662/186410255-617553ef-ce6b-476b-9045-20d88011b47d.png">

**Comment by dzbo** [comment]
https://app.clickup.com/t/2tt5dkb

**Comment by dzbo** [comment]
Feature was implemented, more info in the docs https://docs.lukso.tech/guides/browser-extension/sign-in-with-ethereum
