### ISSUE TITLE
[UP Browser Extension] - Option to enable/disable relay

### ISSUE THREAD

**Issue by catalindavid** [lukso-network/issue-tracker#15]
In the case of quota limit reached, the browser extension becomes unusable, throwing `quota exceeded` error. For testing purposes using the browser extension, a toggle button can be implemented to enable/disable relayer service.

**Comment by dzbo** [comment]
There is no such toggle but you can simply get controller key funds (through [l16 faucet](https://faucet.l16.lukso.network/)) and pay for gas by yourself.

Controller key address is here:
![CleanShot 2022-08-18 at 15 56 39@2x](https://user-images.githubusercontent.com/1100879/185413130-8486b837-eaba-4eea-8c7f-6539cf14f751.png)

Also on latest release the quota was disabled so even using relayer you have no limit anymore.

**Comment by catalindavid** [comment]
thank you
