### ISSUE TITLE
Relayer apiUrl must accept `-` (dash)

### ISSUE THREAD

**Issue by lykhonis** [lukso-network/issue-tracker#16]
**Describe the bug**
Invoking RCP call `up_addRelayService` rejects with error:
```
code: -32602, message: 'Invalid relayer apiUrl'
```

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Invoke the RCP call 'up_addRelayService' with the following:
```
const relayer = {
  name: 'My Relayer',
  apiUrl: 'https://relayer.l16-test.staging.lukso.dev/api/v1/',
  chainIds: [2828],
}
```

I added `l16-test` (dash between).

**Expected behavior**
Should not reject as this is valid url

**Screenshots**
<img width="476" alt="Screen Shot 2022-08-25 at 08 49 50" src="https://user-images.githubusercontent.com/881338/186669118-2befd99a-2a0e-4012-bdcf-1e9a98671355.png">

**Info:**
 - Browser: chrome
 - Version: 1.0.0-develop.298
 - Manifest: ?

**Comment by Hugoo** [comment]
Internal ticket: https://app.clickup.com/t/2ryc1a7

**Comment by Hugoo** [comment]
Hi @lykhonis - this issue has been fixed in the latest release: you can find it here.
https://github.com/lukso-network/docs/pull/392

I let you close the issue if everything works for you ;)

Thanks 🙏
