### ISSUE TITLE
[Web UP Extension] Fix unlock UI

### ISSUE THREAD

**Issue by lykhonis** [lukso-network/issue-tracker#20]
**Describe the bug**
1. Password is always required. There is no option to disable password or set a time for inactivity lock.
2. Password is asked for selecting an account and SIWE, twice. Unlocked period is either not working or too short. Cannot configure it in UI.
3. Window is not focused on password input when presented on a screen. This requires additional user interaction to select password input.

**To Reproduce**
1. Unlock UP extension using dapp
2. Try in few mins (may be less)

**Expected behavior**
1. Do not require password if it was disabled or time is not expired yet web browser was not restarted
2. Do not ask password if extension is unlocked. Ask password once to unlock
3. Focus password input when UP extension is presented for a call to action

**Screenshots**
N/A

**Info:**
N/A

**Comment by Hugoo** [comment]
Internal ticket: https://app.clickup.com/t/338674w

**Comment by jnorbert** [comment]
@lykhonis The issue has been fixed. If you notice any other issues please let us know.
Thank you.
