### ISSUE TITLE
[Browser Extension] Custom controllers

### ISSUE THREAD

**Issue by lykhonis** [lukso-network/issue-tracker#21]
**Is your feature request related to a problem? Please describe.**
We create UP that is owned by multiple people and controlled through some tools/scripts. We would like to own keys/controllers that control UP yet we want to use this UP with our dapp.

**Describe the solution you'd like**
Add a button to controllers in UP extension to add a custom controller key.

**Describe alternatives you've considered**
Deploying UP ourselves and setting up keys without UP extension. Then doing import into UP extension.

**Additional context**
N/A

**Comment by frozeman** [comment]
You could simply make a setDara transaction, adding a controller key with whatever rights. And the user simply confirms this. Not sure why he would need to manually add the key there.

can you describe your use case better?

**Comment by lykhonis** [comment]
> You could simply make a setDara transaction, adding a controller key with whatever rights. And the user simply confirms this. Not sure why he would need to manually add the key there.
> 
> 
> 
> can you describe your use case better?

That's what I did. For people that are not technical but would like to have a common UP (a business profile) I still think it would be beneficial.
