### ISSUE TITLE
Take in account gas provided by app

### ISSUE THREAD

**Issue by lykhonis** [lukso-network/issue-tracker#24]
**Is your feature request related to a problem? Please describe.**
App estimates gas (eth_estimateGas) of a possible transaction. It may adjust gas based on custom rules. Extension should consider gas provided by app as a default option.

**Describe the solution you'd like**
Extension should use `gas` of a transaction if provided by an app

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Hugoo** [comment]
cc @asciiman

**Comment by lykhonis** [comment]
moved to discord
