### ISSUE TITLE
RPC to import profile from app

### ISSUE THREAD

**Issue by lykhonis** [lukso-network/issue-tracker#25]
**Is your feature request related to a problem? Please describe.**
Document API for an app to export a profile into extension. Similar how https://my.universalprofile.cloud creates and then exports profile to extension.

**Describe the solution you'd like**
API spec in https://docs.lukso.tech/guides/browser-extension

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Hugoo** [comment]
@asciiman @biancabuzea200

**Comment by Hugoo** [comment]
RPC calls are described here for the extension 

https://docs.lukso.tech/standards/rpc-api#up_import

But Specs are missing fro this RPC up_generateLsp23Address

cc @biancabuzea200

**Comment by lykhonis** [comment]
> RPC calls are described here for the extension
> 
> https://docs.lukso.tech/standards/rpc-api#up_import
> 
> But Specs are missing fro this RPC up_generateLsp23Address
> 
> cc @biancabuzea200

what I am looking for is something like:
1. app has a controller with change owner permissions of a profile
2. app requests controller address from extension passing profile's address to extension
3. app sets permissions on extension's controller
4. extensions detects permissions set of its controller on the profile
5. profit

**Comment by asciiman** [comment]
You can use `up_generateLsp23Address` for that. We do need to document it though.

**Comment by lykhonis** [comment]
> You can use `up_generateLsp23Address` for that. We do need to document it though.

I am not sure what this call does. But coming back to [up_import](https://docs.lukso.tech/standards/rpc-api/#up_import), from it looks, I assume app can push profile's address, where extension would return controller address. App then would be expected to set permissions for that controller and extension then would recognize it and mark the profile imported. Is that correct?

**Comment by asciiman** [comment]
Exactly. 

`up_import` and `up_generateLsp23Address` both allow a profile to be imported. The difference is, for `up_import` the profile must already exist. You pass it to the extension as you say and we give you back a controller address. 

With `up_generateLsp23Address` you do not already have the profile created. The user gets to pick the profile address in the extension. The controller key is automatically associated. We pass back to you the salt, controller address, and up address and you create it. The point of this is that the transaction can be run on other networks so the user can keep the address on other networks. There is more involved and we're going to work on the documentation for this.
