### ISSUE TITLE
[Web UP Extension] Displays count notification in icon (Chrome)

### ISSUE THREAD

**Issue by lykhonis** [lukso-network/issue-tracker#3]
version: v1.0.0-develop.260-MV3
browser: chrome

Each time UP extension is used, it displays a count in the icon as a badge. Whenever I open extension, this count starts to go down each second, and only then extension window is usable. It seems to create some draft transactions, the count might be related to those.

https://user-images.githubusercontent.com/881338/180912261-6fa40bb7-893c-4bc1-b5f1-ea3ba8831e4d.mov

**Comment by dzbo** [comment]
This is fixed and should be available in next release.
