### ISSUE TITLE
[Relayer Standard] Change quota API

### ISSUE THREAD

**Issue by lykhonis** [lukso-network/issue-tracker#4]
link: https://lukso.notion.site/lukso/Transaction-Relay-Service-API-Standard-2bda58f4f47f4497bb3381654acda8c3

Quota API expects a hash of UNIX timestamp to be signed by a controller of UP. API dictates sending signature, message (hash), and timestamp as part of authorization header.

The following is the proposal:
- Modify how hash is calculated:
  - Use [UP address] + [timestamp] as a string and hash using SHA3
- Do not send message (hash) in authorization
  - Send UP address
  - Hash can be recomputed on server side as [UP Address] + [timestamp]
  - Server can then recover signer (controller) to verify permissions on the [UP address] and poll database per UP/KeyManager as needed

**Comment by frozeman** [comment]
We just changed it yesterday to a POST message request: 
```js
{
  "address": "0xBB645D97B0c7D101ca0d73131e521fe89B463BFD",
  "timestamp": 1656408193,
  "hash": "0xfc24d99642d1654336d597e8fc31b13e710f97e3d1ac170c65cf4dd839398a99",
  "signature": "0xf480c87a352d42e49112257cc6afab0ff8365bb769424bb42e79e78cd11debf24fd5665b03407d8c2ce994cf5d718031a51a657d4308f146740e17e15b9747ef1b"
}
```

The API was not fully thought out, and we forgot to add the UP address there :)

**Comment by frozeman** [comment]
But you are correct, the hash should be the UP address + timestamp `keccack256(address, timestamp)`

**Comment by lykhonis** [comment]
> We just changed it yesterday to a POST message request:
> 
> ```js
> {
>   "address": "0xBB645D97B0c7D101ca0d73131e521fe89B463BFD",
>   "timestamp": 1656408193,
>   "hash": "0xfc24d99642d1654336d597e8fc31b13e710f97e3d1ac170c65cf4dd839398a99",
>   "signature": "0xf480c87a352d42e49112257cc6afab0ff8365bb769424bb42e79e78cd11debf24fd5665b03407d8c2ce994cf5d718031a51a657d4308f146740e17e15b9747ef1b"
> }
> ```
> 
> The API was not fully thought out, and we forgot to add the UP address there :)

Could we:
1. Remove hash, as it should be recomputed on server side
2. Specify keccack256 as hash mechanism in API. Could we use SHA3 instead?

Thanks!

**Comment by frozeman** [comment]
We could remove the hash, makes sense. @CallumGrindle. So only:
```js
{
  "address": "0xBB645D97B0c7D101ca0d73131e521fe89B463BFD",
  "timestamp": 1656408193,
  "signature": "0xf480c87a352d42e49112257cc6afab0ff8365bb769424bb42e79e78cd11debf24fd5665b03407d8c2ce994cf5d718031a51a657d4308f146740e17e15b9747ef1b"
}
```

To calculate the hash, we should use the solidity way: https://web3js.readthedocs.io/en/v1.7.4/web3-utils.html#soliditysha3
`web3.utils.soliditySha3('0x23456...', 1234567)`

This way its also future compatible to smart contracts

I also tested if it makes a difference between address and just auto detection, and out comes the same hash, so that should be dev friendly.

<img width="741" alt="Screenshot 2022-07-21 at 15 18 26" src="https://user-images.githubusercontent.com/232662/180223194-84f85b4b-581b-401d-984d-04b81e20f48b.png">

**Comment by CallumGrindle** [comment]
Nice yes this makes sense. Thanks @lykhonis for the suggestions!

**Comment by Hugoo** [comment]
Internal task id: `#2r740bh`

**Comment by Hugoo** [comment]
This issue has been fixed. Closing.

**Comment by Hugoo** [comment]
> Also sha256, is the default for almost anything in ethereum, so it makes sense to use this hashing method

you meant sha3 / keccak256 right?
