### ISSUE TITLE
[Web UP Extension] Crash if gas is NaN

### ISSUE THREAD

**Issue by lykhonis** [lukso-network/issue-tracker#6]
UP extension crashes if gas set to NaN (not a number) when sending a tx
![Screen_Shot_2022-07-23_at_09 57 50](https://user-images.githubusercontent.com/881338/180608352-f84f7692-1767-451f-a58d-d0975e00a3a2.png)

**Comment by lykhonis** [comment]
I think problem comes down to UP extension not being able to decode revert messages

**Comment by Hugoo** [comment]
This issue has been added in our internal tracking system: `#2p6rxk1`

**Comment by dzbo** [comment]
It's hard to know without seeing the error. We've made a fix for this "unreadable" errors, you will be able to check in next release. `NaN` doesn't seem to be a problem here as such transaction pass trough:

```js
await window.ethereum.request({method:'eth_sendTransaction', params:[{from:'0x9Bbc7e94e93e09Ae54f3DDC25c7Db4F97d1Cd427', to:'0x9Aa8f07A670dA09C7b0eb93a3AE7Beb6159Cf080', value:'0x38D7EA4C68000', gas:NaN}]});
```

Might be something related to permissions/funds.
