### ISSUE TITLE
UP web extension creates profiles on L14

### ISSUE THREAD

**Issue by JordyDutch** [lukso-network/issue-tracker#7]
I’m using version v1.0 of the UP web extension which I downloaded from docs.lukso.tech. Using it on MacOS 12.4 on the latest Microsoft Edge browsers. I have the following problems:

- All profiles created on L14
- When I create a new profile it sometimes delete other profiles
- Sometimes the extension delete itself from my browser and I lose all my UP’s

![6B087DA3-1E95-4596-BD22-3CA410AD7A5E](https://user-images.githubusercontent.com/85904689/180995278-2985f8c9-4263-4fb8-97e2-f342109e6a1a.png)

**Comment by jakeprins** [comment]
Could you check the full version number? Do you have `1.0.0-develop.260` and disabled/removed other versions?

![CleanShot 2022-07-26 at 14 53 20](https://user-images.githubusercontent.com/17762366/181010596-40f7a76b-8a41-4acf-b1d7-d8628957ffde.png)


`

**Comment by JordyDutch** [comment]
Thanks Jake, apparently we have a lot of different v1.0’s 😅😅 Very clear. I really thought I installed the latest version which I downloaded from lukso.docs.tech.

Fixed now 👍🏼

**Comment by fhildeb** [comment]
💜 Thanks for the quick response @jakeprins
