### ISSUE TITLE
UP web extension deletes itself when uploading the ZIP file

### ISSUE THREAD

**Issue by JordyDutch** [lukso-network/issue-tracker#8]
When I drag the ZIP file into the extensions page it removes itself after restarting my Mac mini.

When I load the unpacked file it is fine and keeps working.

Tested this on Brave and Edge

**Comment by Hugoo** [comment]
It looks like this is out of our scope.

To install the UP extension, simply click on "Load unpacked" as [described in our docs](https://docs.lukso.tech/guides/browser-extension/install-browser-extension/).

The behavior related to dragging or not a ZIP file on the browser extension page (be it Chrome, Brave, Edge...) is outside of our responsibility.

**Comment by JordyDutch** [comment]
Lol 😅

![C298B740-365D-412D-BA80-A3E9686A3370](https://user-images.githubusercontent.com/85904689/181121275-4174d217-e50d-49e2-a895-1d02830c4067.jpeg)

**Comment by Hugoo** [comment]
My bad @JordyDutch 😟 ! I will edit our docs!
Thanks for spotting!

**Comment by Hugoo** [comment]
I pushed the fix here: <https://github.com/lukso-network/docs/pull/314>
